<?php

namespace ContainerGhNLkY8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XvRQOj0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xvRQOj0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xvRQOj0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactForm' => ['privates', '.errored..service_locator.xvRQOj0.App\\Entity\\ContactForm', NULL, 'Cannot autowire service ".service_locator.xvRQOj0": it needs an instance of "App\\Entity\\ContactForm" but this type has been excluded in "config/services.yaml".'],
        ], [
            'contactForm' => 'App\\Entity\\ContactForm',
        ]);
    }
}
