<?php

namespace ContainerDS3owWM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RJuivJhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rJuivJh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rJuivJh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'crud' => ['privates', '.errored.tD03KEI', NULL, 'Cannot determine controller argument for "App\\Controller\\ContactFormController::configureCrud()": the $crud argument is type-hinted with the non-existent class or interface: "App\\Controller\\Crud". Did you forget to add a use statement?'],
        ], [
            'crud' => '?',
        ]);
    }
}
