<?php

namespace ContainerDS3owWM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactForm2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xvRQOj0.App\Entity\ContactForm' shared service.
     *
     * @return \App\Entity\ContactForm
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xvRQOj0": it needs an instance of "App\\Entity\\ContactForm" but this type has been excluded in "config/services.yaml".');
    }
}
