<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_contact_form_index' => [[], ['_controller' => 'App\\Controller\\ContactFormController::index'], [], [['text', '/admin/user/contact_form_list']], [], [], []],
    'app_contact_form_new' => [[], ['_controller' => 'App\\Controller\\ContactFormController::new'], [], [['text', '/']], [], [], []],
    'app_contact_form_show' => [['id'], ['_controller' => 'App\\Controller\\ContactFormController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/list']], [], [], []],
    'app_contact_form_edit' => [['id'], ['_controller' => 'App\\Controller\\ContactFormController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/list']], [], [], []],
    'app_contact_form_delete' => [['id'], ['_controller' => 'App\\Controller\\ContactFormController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/list']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/admin/user/list']], [], [], []],
    'app_user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/admin/user/new']], [], [], []],
    'app_user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
    'app_user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
    'app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user']], [], [], []],
];
